---
# Handler for the webtier: handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: restart php-fpm
  service:
    name="{{ php5-fpm_service }}"
    state=restarted

- name: reload php-fpm
  service:
    name="{{ php5-fpm_service }}"
    state=reloaded

- name: restart apache
  service:
    name: "{{ apache_service }}"
    state: restarted
